spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS}
      secret-key: ${AWS_S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_exp: ${JWT_ACCESS_EXP:7200}
  refresh_exp: ${JWT_REFRESH_EXP:26400}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}
  algorithm: ${JWT_ALGORITHM:HS256}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    number: ${SMS_NUMBER}

file:
  upload-dir: /path/to/upload/directory